### PR TITLE
Check if environ['CONTENT_LENGTH'] not empty.

### PR DESCRIPTION
**Pull request by KoleS46**

### CODE REVIEW

**Comment by tseaver** [comment]
Thanks for the patch!  Could you add a test which exercises the new condition?

Maybe the check would be clearer as:

```python
if environ.get('CONTENT_LENGTH', None) not in (None, ''):
```

Also, in what cases have you seen the empty string for the header?  I see that PEP 333 [allows a WSGI server to supply an empty `Content-Length`](https://www.python.org/dev/peps/pep-0333/#environ-variables), although I cannot think of any reason to pass through a "bogus" value.

**Comment by KoleS46** [comment]
No problem! I just have to find some spare time :).

```python
if environ.get('CONTENT_LENGTH') not in (None, ''):
```
would be better, `get` returns `None` as a default value.

**Comment by celeraone** [comment]
Hi, what is the status of this pull request? We would be more than happy to if it could be merged upstream. Thanks in advance!

**Comment by tseaver** [comment]
@celeraone see my request above for a unit test, as well as confirmation as to which WSGI server is setting the `CONTENT_LENGTH` environment variable to an empty string.

**Comment by KoleS46** [comment]
@tseaver The test has finally made it to the change. Sorry for the delay.
As for the confirmation of which server is setting an empty value I can't remember which one was it.

**Comment by tseaver** [comment]
@KoleS46  Thanks again for the patch!

**Pull request merged**
